select private.generate_workbook_topic_questions('Grade 7','Addition and Subtraction of Numbers');
select private.generate_workbook_topic_questions('Grade 7','Squaring No’s Ending With 0');
select private.generate_workbook_topic_questions('Grade 7','Squaring No’s Ending With 1');
select private.generate_workbook_topic_questions('Grade 7','Squaring No’s Ending With 5');
select private.generate_workbook_topic_questions('Grade 7','Percentages');
select private.generate_workbook_topic_questions('Grade 7','Mezzoscopic Tens and Ones');
select private.generate_workbook_topic_questions('Grade 7','Multiplying by 9');
select private.generate_workbook_topic_questions('Grade 7','Summary Worksheet');
select private.generate_workbook_topic_questions('Grade 7','Division by 5');
select private.generate_workbook_topic_questions('Grade 7','Division by 50');
select private.generate_workbook_topic_questions('Grade 7','Division by 500');
select private.generate_workbook_topic_questions('Grade 7','Multiplying numbers ending with 0');
select private.generate_workbook_topic_questions('Grade 7','Multiplying numbers ending with 1');
select private.generate_workbook_topic_questions('Grade 7','Multiplying by 22');
select private.generate_workbook_topic_questions('Grade 7','Division by 2');
select private.generate_workbook_topic_questions('Grade 7','Multiplication by 5');
select private.generate_workbook_topic_questions('Grade 7','Multiplication by 50');
select private.generate_workbook_topic_questions('Grade 7','Multiplication by 500');
select private.generate_workbook_topic_questions('Grade 7','Division by 9');
select private.generate_workbook_topic_questions('Grade 7','Divisibility Rules ( 5 – 10)');
select private.generate_workbook_topic_questions('Grade 7','Summary Worksheet & BECE Sample Questions');